services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: construction_management_jwt_secret_2024_secure_key
      COMPANY_NAME: 建設發包管理系統
      COMPANY_EMAIL: admin@construction-demo.com
      PASSWORD: PxtBr891A52MeRHJv3KNno04U6OzZDg7